package com.myorg.poc.bp.loan_process_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanApplicationDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label("panNumber")
	private java.lang.String panNumber;
	@org.kie.api.definition.type.Label("passportNumber")
	private java.lang.String passportNumber;
	@org.kie.api.definition.type.Label("loanAmount")
	private java.lang.Float loanAmount;
	@org.kie.api.definition.type.Label("loanInterestRate")
	private java.lang.Float loanInterestRate;
	@org.kie.api.definition.type.Label("loanTenure")
	private java.lang.Float loanTenure;

	@org.kie.api.definition.type.Label(value = "formValidationResult")
	private java.lang.Boolean formValidationResult;

	public LoanApplicationDetails() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getPanNumber() {
		return this.panNumber;
	}

	public void setPanNumber(java.lang.String panNumber) {
		this.panNumber = panNumber;
	}

	public java.lang.String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(java.lang.String passportNumber) {
		this.passportNumber = passportNumber;
	}

	public java.lang.Float getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(java.lang.Float loanAmount) {
		this.loanAmount = loanAmount;
	}

	public java.lang.Float getLoanInterestRate() {
		return this.loanInterestRate;
	}

	public void setLoanInterestRate(java.lang.Float loanInterestRate) {
		this.loanInterestRate = loanInterestRate;
	}

	public java.lang.Float getLoanTenure() {
		return this.loanTenure;
	}

	public void setLoanTenure(java.lang.Float loanTenure) {
		this.loanTenure = loanTenure;
	}

	public java.lang.Boolean getFormValidationResult() {
		return this.formValidationResult;
	}

	public void setFormValidationResult(java.lang.Boolean formValidationResult) {
		this.formValidationResult = formValidationResult;
	}

	public LoanApplicationDetails(java.lang.String name,
			java.lang.String address, java.lang.String panNumber,
			java.lang.String passportNumber, java.lang.Float loanAmount,
			java.lang.Float loanInterestRate, java.lang.Float loanTenure,
			java.lang.Boolean formValidationResult) {
		this.name = name;
		this.address = address;
		this.panNumber = panNumber;
		this.passportNumber = passportNumber;
		this.loanAmount = loanAmount;
		this.loanInterestRate = loanInterestRate;
		this.loanTenure = loanTenure;
		this.formValidationResult = formValidationResult;
	}

}