camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks

camunda:
  dummyWebservice:
    panValidationUrl: http://localhost:8081/pan/validate